name: Danger
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:
  push:
    branches:
      - feature/*
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Setup gems
      run: |
        gem install bundler -v "1.16.1"
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
